### ISSUE TITLE
Issue while Unwrapping an Optional value

### ISSUE THREAD

**Issue by prashanth555** [KrisYu/LivelyGIFs#1]
Hi ,

When I tried running this project on my Simulator, i am getting the following error. Why is that?. Can you help me?

 LivelyGIFs[4088:1791538] *** error reading settings archive file: <ISRootSettings: /var/mobile/Containers/Data/Application/F69DA58F-A021-4D45-88D1-345419E1AFFD/Documents/com.xueyu.LivelyGIFs.settings/ISRootSettings_10.plist>
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-06-07 21:22:36.988181-0500 LivelyGIFs[4088:1791538] fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb)

**Comment by KrisYu** [comment]
Hi, you can't actually use live photo in Simulator, you have to test on a real device.

Thx.
